### PR TITLE
refactor & improve CI

### PR DESCRIPTION
**Pull request by philbucher**

### CODE REVIEW

**Comment by philbucher** [comment]
this requires #29 

also there are some linking problems with Clang :thinking: I also have them locally

**Comment by philbucher** [comment]
@phmkopp any clue why it gives a linker error in Clang?
~~~
[100%] Linking CXX executable vtu11_testrunner
/usr/bin/ld: CMakeFiles/vtu11_testrunner.dir/test/main_test.cpp.o: in function `Catch::Detail::Approx::toString[abi:cxx11]() const':
main_test.cpp:(.text+0x174): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
/usr/bin/ld: main_test.cpp:(.text+0x1b8): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
~~~

I get the same locally, no clue why

**Comment by phmkopp** [comment]
Not off the top of my head, no.

**Comment by philbucher** [comment]
turns out that it works if I use the C++ compiler as opposed to the C compiler (clang++ vs clang)
:man_facepalming:

**Comment by philbucher** [comment]
In any case, this PR is ready

I also updated the Catch2 header and added a missing include guard

@phmkopp In order for this to be merged you need to change the required builds in the branch protection rules. Do you know how to do that?

**Comment by phmkopp** [comment]
Like this?

**Comment by philbucher** [comment]
yes, cool, thx

**Pull request merged**
