### PR TITLE
Move catch include

### PR DESCRIPTION
**Pull request by philbucher**
Are you ok with the relative paths? Otherwise we need to also include the root-dir in CMake
I think this solution is ok

### CODE REVIEW

**Comment by phmkopp** [comment]
why?

**Comment by philbucher** [comment]
IMO the `vtu11` folder should only contain the actual implementation, to me it is cleaner if external libs are in a different folder

**Comment by phmkopp** [comment]
No, I mean why rename the folder?

**Comment by philbucher** [comment]
I didn't rename it, I moved it outside of the vtu11 folder:
 vtu11/external/catch2/catch.hpp → external_libraries/catch2/catch.hpp

**Comment by phmkopp** [comment]
Ah, makes sense now. But can't we just put it into the test folder then?

**Comment by philbucher** [comment]
> But can't we just put it into the test folder then?

would also be fine for me
I just find it clean if all ext-libraries are in one place but I don't really care :)

**Comment by phmkopp** [comment]
Ok, but now we have 

/external_libraries
/vtu11/external

... which is confusing to me, what does contain what? With your suggestion we should move everything from vtu11/external to /external. But then the core depends on some of those, so moving them out of vtu11 doesn't make sense to me. My interpretation is that 

/external_libraries -> test libraries, what other libraries are not needed by the core?
/vtu11/external -> core dependencies

And as in that setting only the test stuff would be in external_libraries, I think is the best to just put it in test/. 

Or?

And for relative paths ... I think with my proposal that would be irrelevant anyway, right? I don't have any issues with relative paths, but in a general setting I think relative paths with ../../ are less flexible than absolute paths starting from the include directories. With those you can easily swap out different implementations and have something point to /usr/include/ if need be.

**Comment by philbucher** [comment]
> But then the core depends on some of those

yes, that how Kratos does it (not saying this is right or wrong)

But I am also perfectly fine with moving catch to `test` and `filesystem to `vtu11/external`
Then the core wouldn't depend on anything else, sounds good to me

**Comment by phmkopp** [comment]
Well, I think both variants are fine

1. having only a single /external where we put everything including catch2 
2. keeping vtu11/external with core dependencies and catch2 in test/

I don't know ... choose what you prefer? I personally like the naming external more than external_libraries, but I guess that is personal preference.

**Comment by philbucher** [comment]
I used the second option: keeping vtu11/external with core dependencies and catch2 in test/

**Pull request merged**
