### PR TITLE
Set buffer size and use snprintf to write ascii

### PR DESCRIPTION
**Pull request by phmkopp**

### CODE REVIEW

**Comment by phmkopp** [comment]
This is ~10 times faster for ascii and maybe 10% faster for the other stuff because of the larger buffersize. For my test case.

**Comment by philbucher** [comment]
> This is ~10 times faster for ascii and maybe 10% faster for the other stuff because of the larger buffersize. For my test case.

cool!

how so? can you explain briefly?

**Comment by philbucher** [comment]
BTW I also noticed that you always open the file in binary mode:
https://github.com/phmkopp/vtu11/blob/3dd54888f14315f919c546b2d022ab8cd4167269/vtu11/impl/vtu11_impl.hpp#L108

this is also used for ascii no?

How does this work?

**Comment by phmkopp** [comment]
> How does this work?
As far as I know binary and text mode only differ in the way new lines are added.

**Review by philbucher — APPROVED** [review]

**Comment by phmkopp** [comment]
> cool!
> 
> how so? can you explain briefly?

Hmm, idk, but it works. :)

Well I found this: https://stackoverflow.com/questions/445315/why-is-snprintf-faster-than-ostringstream-or-is-it

The benchmark results linked there are not as extreme as it was on my example, but go in the same direction.

**Pull request merged**
